### ISSUE TITLE
ModuleNotFoundError: No module named 'okta.client'; 'okta' is not a package

### ISSUE THREAD

**Issue by saloni-canva** [okta/okta-sdk-python#273] opened 2022-02-04 12:04 UTC
I have installed okta python package using ```pipenv install okta``` and am running a virtual environment with okta installed. I am trying to run the sample example code that was provided 

``` 
import constants
import asyncio
from okta.client import Client as OktaClient

# Instantiating with a Python dictionary in the constructor
config = {
    'orgUrl': constants.OKTA_URL,
    'token': constants.OKTA_TOKEN
}
okta_client = OktaClient(config)

# example of usage, list all users and print their first name and last name
async def main():
    users, resp, err = await okta_client.list_users()
    for user in users:
        print(user.profile.first_name, user.profile.last_name)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

However I am getting this error 
```
ModuleNotFoundError: No module named 'okta.client'; 'okta' is not a package
```
Can you help? Thanks

**Comment by serhiibuniak-okta** [comment] 2022-02-04 12:47
@saloni-canva Could you please check if package was installed correctly and/or import refers to correct file. First, you can do the following within Python interpreter:
```py
>>> import okta
>>> okta.__file__
# it should print something like the following
'<YOUR WORK DIR>venv/lib/python<YOUR PYTHON VER>/site-packages/okta/__init__.py'
```
Then you can check if that folder has file `client.py` alongside with `__init__.py`.

**Comment by saloni-canva** [comment] 2022-02-04 13:40
So I ran okta.__file__ and it printed the directory ![image](https://user-images.githubusercontent.com/90663513/152538189-eb043187-a543-4c60-94d5-4dcf41e37b39.png)

From there, I found client.py 
![image](https://user-images.githubusercontent.com/90663513/152538234-64599c7e-ee80-486b-a368-76247724539a.png)

Is it something to do with running python / python3+ or pipenv ?  This is the command I am using to run the okta.py file 
![image](https://user-images.githubusercontent.com/90663513/152538480-4f1b7f73-82bd-4ac4-9228-22cd626c9203.png)

**Comment by serhiibuniak-okta** [comment] 2022-02-04 14:04
I guess, in this case it tries to import client from your file "okta.py", not from package "okta". By default, python import looks first in local directory, so you can play with paths or rename your file "okta.py" to anything else, for example "test_okta.py" and try again.

**Comment by saloni-canva** [comment] 2022-02-07 02:46
Thanks its working now! Is there any way I can rename to okta.py in the future e.g by making file first then installing package? I've done this for Jira as well with a jira.py file and its working fine

**Comment by serhiibuniak-okta** [comment] 2022-02-07 08:36
You can install packages without any problem. The issue is in `import`. To sort things out you can start from https://docs.python.org/3/reference/import.html
I'm closing this issue as it has nothing to do with this repo and okta package.

**Closed by serhiibuniak-okta** 2022-02-07 08:36 UTC
