### ISSUE TITLE
Module won't load in Python 3.3+

### ISSUE THREAD

**Issue by stevenhair** [okta/okta-sdk-python#7] opened 2015-10-20 18:02 UTC
Python 3.3 [dropped support for implicit relative imports](https://docs.python.org/3/reference/import.html) in accordance with [PEP 302](http://www.python.org/dev/peps/pep-0302), which breaks this package. This can be fixed by making all relative imports explicit - e.g. `from User import User` should be changed to `from .User import User` in `okta/models/user/__init__.py`. Explicit relative imports are supported in Python 2.7, so this change should not break anything.

**Comment by jmelberg-okta** [comment] 2017-01-13 22:21
Hi @stevenhair. We apologize for the long delay.

We are currently in the process of updating this project. In the meantime, there is a possible fix [described here](https://github.com/okta/oktasdk-python/issues/10).

Thanks!

**Comment by jmelberg-okta** [comment] 2017-06-23 18:59
@stevenhair  - Closing this as it is a duplicate of #9.

**Closed by jmelberg-okta** 2017-06-23 18:59 UTC
Labels: bug
