### ISSUE TITLE
Can't get values for existing custom attributes

### ISSUE THREAD

**Issue by DREW1990** [okta/okta-sdk-python#160] opened 2020-12-29 23:40 UTC
When using the Okta User API (`/api/v1/users/${userId}`) with `requests` or Postman, I'm able to retrieve all attributes, including existing custom attributes.

When using the SDK I only get a predefined list of attributes from the `UserProfile` class. The README mentions how to modify `UserProfile` and set new values for a custom attribute. However, I can't figure out a way to retrieve existing values for custom attributes.

**Comment by arvindkrishnakumar-okta** [comment] 2020-12-30 02:13
@DREW1990 Thanks for your question! Our Python SDK team will follow-up on this after the holidays.

**Comment by serhiibuniak-okta** [comment] 2020-12-30 08:55
@DREW1990 Could you please, provide more details? (i.e. some code, sample output, etc.)
Full example under this section https://github.com/okta/okta-sdk-python#get-and-set-custom-attributes shows how to get custom attribute. It should be accessible via <user_obj>.profile.<custom_attribute_name>.

**Comment by DREW1990** [comment] 2020-12-30 17:20
Here's an example using `requests` to get an existing custom attribute (`badgeNumber`) from a user:

```
def get_badge_number(user):
    url = f'{okta_url}/api/v1/users/{user}'
    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
        "Authorization": f"SSWS {okta_token}",
    }

    response = requests.get(url, headers=headers)
    print(response.json()['profile']['badgeNumber'])
```
Which returns a string of numbers.

However, when using the Okta SDK, I'm unable to retrieve the value for `badgeNumber`:
```
async def get_badge_number(user):
    user_info, response, error = await client.get_user(user)
    print(user_info.profile.badgeNumber)
```
This results into an error: `AttributeError: 'UserProfile' object has no attribute 'badgeNumber'`

The example in the README  shows how to assign and create a custom attributes. However, I couldn't find a way to get any existing custom attributes. Maybe I just need more guidance on how to pull the information with the SDK?

**Comment by serhiibuniak-okta** [comment] 2020-12-30 17:36
@DREW1990 Thank you for detailed response.
Currently, for variables set via config we use lowerCamelCase, but for object attributes (i.e. pythonic-way) snake_case.
Could you please, try access that value in the following way:
```py
user_info.profile.badge_number
```
?
I believe, that's the way how it worked previously with regular attributes, i.e. described in model, like `firstName` and `first_name`.

**Comment by DREW1990** [comment] 2020-12-30 17:50
Thanks for the quick response! Unfortunately that didn't work either:
```
async def okta_employee(user):
    user_info, response, error = await client.get_user(user)
    print(user_info.profile.badge_number)
```

`AttributeError: 'UserProfile' object has no attribute 'badge_number'`

**Comment by serhiibuniak-okta** [comment] 2020-12-30 18:31
Hmm, could you please, show the output of `print(user_info.profile)`? Maybe, some clue is inside

**Comment by DREW1990** [comment] 2020-12-30 18:48
For privacy reasons I can't show the full output. But I did extract all of the keys.

Here are the list of `profile` keys that get returned when using the SDK:
```
city
cost_center
country_code
department
display_name
division
email
employee_number
first_name
honorific_prefix
honorific_suffix
last_name
locale
login
manager
manager_id
middle_name
mobile_phone
nick_name
organization
postal_address
preferred_language
primary_phone
profile_url
second_email
state
street_address
timezone
title
user_type
zip_code
```

When using the Okta API directly with requests, it will only show the attributes that are not `None`. I get the following keys:

```
lastName
city
displayName
badgeNumber
subDepartment
title
login
employeeNumber
division
officeLocation
mobilePhoneCountryCode
company
state
department
email
hireDate
manager
costCenter
secondEmail
managerId
team
firstName
employeeType
mobilePhone
userType
```

Here are the custom attributes that we set in Okta:
![Screen Shot 2020-12-30 at 10 45 50 AM](https://user-images.githubusercontent.com/7978923/103374343-32050a00-4a8c-11eb-848b-36b09568ad66.png)

**Comment by serhiibuniak-okta** [comment] 2020-12-30 18:53
Thank you for all the details. Very interesting, looks like a bug. Let me investigate it. Are you unblocked using requests?

**Comment by DREW1990** [comment] 2020-12-30 18:56
Awesome, thanks for the help! And nope, I can use requests for now. My team is just looking forward to using the Okta SDK for our projects going forward so we have some sort of consistency in our projects.

**Comment by serhiibuniak-okta** [comment] 2020-12-30 19:03
Glad to hear that! But we will be able to release new version with fix only after all holidays. Feel free to add anything to this issue you find might be useful.

**Comment by serhiibuniak-okta** [comment] 2021-01-08 12:35
@DREW1990 I can't reproduce the error.
I've added attribute and it works for me:
<img width="1108" alt="Screenshot 2021-01-08 at 14 16 59" src="https://user-images.githubusercontent.com/73126645/104016300-be1ade00-51be-11eb-8321-2e8844e4352d.png">


Could you please try run the following script with your config?
```py
from okta.client import Client as OktaClient
import asyncio

async def main():
    client = OktaClient()
    users, resp, err = await client.list_users()
    for user in users:
        try:
            print(f'{user.profile.first_name} has Badge Number: {user.profile.badge_number}')
        except:
            print(f'{user.profile.first_name} has no Badge Number.')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
my output:
```sh
John has Badge Number: 123
Serhii has no Badge Number.
```

**Comment by serhiibuniak-okta** [comment] 2021-01-25 19:02
@DREW1990 I am going to close this issue as resolved, because I can't reproduce the issue: it works for me with `client.get_user`, `client.list_users`, etc. But please reach out to us if you find that your issue still exists.

**Closed by serhiibuniak-okta** 2021-01-25 19:02 UTC
Labels: bug
